apiVersion: v1
kind: Pod
metadata:
  labels:
    run: volume
  name: volume
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /safeprofile
      name: primeiro-emptydir
    resources:
      limits:
        cpu: "1.0"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 256Mi
