apiVersion: v1
kind: Pod
metadata:
  labels:
    run: safeprofile
  name: safeprofile
spec:
  containers:
  - name: resource-limit-container
    image: busybox
    volumeMounts:
    - mountPath: /limit-container
      name: limit-container
    args:
      - sleep
      - "600"
    resources:
      limits:
        cpu: "0.3"
        memory: "64Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /nginx-dir
      name: nginx-dir
    resources:
      limits:
        cpu: "1.0"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: nginx-dir
    emptyDir:
      sizeLimit: 256Mi
  - name: limit-container
    emptyDir:
      sizeLimit: 64Mi
